### ISSUE TITLE
Проблемы с логом урона

### ISSUE THREAD

**Issue by DJarovoj** [Armagomen/battle_observer#11]
Добрый день. После патча 1.16.1 перестали работать логи урона. Перестали отображаться значения, так же логи полученного и нанесенного урона тоже не работают.

**Comment by Kurzdor** [comment]
Пробуй версию 1.37.7, исправили если ты про логи самого мода.
В самой игре могут быть проблемы с ВГшные дамаг логами даже без модов. Это известная проблема

**Comment by DJarovoj** [comment]
> Пробуй версию 1.37.7, исправили если ты про логи самого мода. В самой игре могут быть проблемы с ВГшные дамаг логами даже без модов. Это известная проблема

Да, спасибо. Все заработало. Можно закрывать проблему.

**Comment by popszver35** [comment]
Добрый вечер!!! последние обновление.не работает
![shot_003](https://user-images.githubusercontent.com/80174327/163625099-11504b9a-0a8e-4c55-bc0b-76a6554ff259.jpg)
![shot_004](https://user-images.githubusercontent.com/80174327/163625102-4229b59b-d9d4-4adf-bf5b-b37d9b9f1f6f.jpg)
![shot_005](https://user-images.githubusercontent.com/80174327/163625104-987d8a48-c672-4be6-9ced-ed3541180a46.jpg)
![shot_006](https://user-images.githubusercontent.com/80174327/163625106-528bb609-d82c-4aea-b6e2-06ff07ffa636.jpg)
 настройки мода в игре и вообще мод не работает после обновы 1,37,7  нету настроек мода в игре

**Comment by DJarovoj** [comment]
Так же в логе урона перестал отображаться вид снаряда, которым стреляет противник.

**Comment by Kurzdor** [comment]
@DJarovoj исправил, когда релизнется - без понятия

**Comment by DJarovoj** [comment]
> @DJarovoj исправил, когда релизнется - без понятия

Спасибо! Буду ждать...
