### ISSUE TITLE
Не отображается мод в игре.

### ISSUE THREAD

**Issue by Alba123456** [Armagomen/battle_observer#13]
Привет, после обновления 1.37.7 мод в игре не отображается! На 1.37.1 всё работало, кроме лога урона. Возможно это связано с тем, что корневая папка с игрой, находится не на "С" диске? Как с этим быть?

**Comment by popszver35** [comment]
> Привет, после обновления 1.37.7 мод в игре не отображается! На 1.37.1 всё работало, кроме лога урона. Возможно, это связано с тем, что корневая папка с игрой находится не на диске "С"? Как с этим быть?

Добрый!!!! я скинул скрины там все видно  после обновы нет  настроек моды в самой игре

**Comment by popszver35** [comment]
1.37.1 работает а  1.37.7   нет   как исправить или подскажите  игра установлена нормально

**Comment by popszver35** [comment]
![shot_003](https://user-images.githubusercontent.com/80174327/163626099-81e2387c-63af-4d07-832b-579db6e81b4d.jpg)
![shot_006](https://user-images.githubusercontent.com/80174327/163626101-87594c50-4458-438f-95d6-449bea5a48b3.jpg)

**Comment by popszver35** [comment]
Добрый вечер!!! последние обновление.не работает
![shot_003](https://user-images.githubusercontent.com/80174327/163625099-11504b9a-0a8e-4c55-bc0b-76a6554ff259.jpg)
![shot_004](https://user-images.githubusercontent.com/80174327/163625102-4229b59b-d9d4-4adf-bf5b-b37d9b9f1f6f.jpg)
![shot_005](https://user-images.githubusercontent.com/80174327/163625104-987d8a48-c672-4be6-9ced-ed3541180a46.jpg)
![shot_006](https://user-images.githubusercontent.com/80174327/163625106-528bb609-d82c-4aea-b6e2-06ff07ffa636.jpg)
 настройки мода в игре и вообще мод не работает после обновы 1,37,7  нету настроек мода в игре

_Originally posted by @popszver35 in https://github.com/Armagomen/battle_observer/issues/11#issuecomment-1100323505_

**Comment by Armagomen** [comment]
Мод заблокирован для пользователей из РФ - Навсегда.

**Comment by Alba123456** [comment]
хахаха красава)))

**Comment by popszver35** [comment]
я с харькова с украины

**Comment by Alba123456** [comment]
закрывай тему)

**Comment by popszver35** [comment]
вы хотябы скрины  посмотрели  а потом расказывали всякую фигню  версия 1,37,1 работала  а последння нет настроек мода как исправить

**Comment by popszver35** [comment]
> Мод заблокирован для пользователей из РФ - Навсегда.

я  из Харькова .

**Comment by popszver35** [comment]
> Мод заблокирован для пользователей из РФ - Навсегда.

жаль что мод не работает хотя я с украины
