### ISSUE TITLE
Обновления с 1.37.1

### ISSUE THREAD

**Issue by RoffDaniel** [Armagomen/battle_observer#17]
Что изменилось в моде, что после обновления на версию выше 1.37.1? Мод перестаёт работать, если ставить версию 1.37.2+ (на момент написания этого сообщения, последняя версия 1.37.8)

**Comment by popszver35** [comment]
### https://wotsite.net/mody-dlya-world-of-tanks/12150-novaya-panel-scheta-c-indikatorom-obshchego-kolichestva-hp-komand.html скачай отсюда и все будет работать
