### ISSUE TITLE
Патч 1.17

### ISSUE THREAD

**Issue by DJarovoj** [Armagomen/battle_observer#19]
Добрый вечер. Будет ли обновление под патч 1.17?

**Comment by Kurzdor** [comment]
Привет, оно пока что только в Discord. Только оттуда его можно скачать.

**Comment by DJarovoj** [comment]
> Привет, оно пока что только в Discord. Только оттуда его можно скачать.

Привет. Можешь дать линку? Или как найти?

**Comment by Kurzdor** [comment]
https://discord.gg/RBNfr9JWxZ

**Comment by Kurzdor** [comment]
https://discord.gg/ScGfNHDWnW

**Comment by DJarovoj** [comment]
> @DJarovoj https://discord.gg/ScGfNHDWnW

Истек срок приглашения или не действительна ссылка(

**Comment by Kurzdor** [comment]
[https://discord.gg/5Me8cjFQpE](https://discord.gg/5Me8cjFQpE)
видимо кто-то был быстрее тебя

**Comment by DJarovoj** [comment]
> 



> https://discord.gg/5Me8cjFQpE видимо кто-то был быстрее тебя

Спасибо)

**Comment by serzhant04152** [comment]
А можете мне кинуть ссылку на приглашение в Discord
