### ISSUE TITLE
Проблема с лампой 6 чувство

### ISSUE THREAD

**Issue by serzhant04152** [Armagomen/battle_observer#22]
установил  Ваш шикарнейший мод. Пользуюсь уже не первый год. никогда не было проблем, а теперь когда в настройках мода ставлю лампочку 6 чувства, то при засвете вылазит 2 лампочки < одна от вашего мода , с отсчеттом времени ,а  вторая от Wg или  XVM. Стоит XVM. Раньше не было таких траблов а теперь хз в чем косяк. Хотя пробовал ставить Ваш мод и больше ничего все равно 2 лампочки вылазит при засвете. Подскажите если это в XVM  то в каком конфиге что подшаманить или в чем тут проблема?? прошу помощи. заранее спс.

**Comment by serzhant04152** [comment]
киньте ссылку плиз на добавление в Дискорд

**Comment by Armagomen** [comment]
https://discord.gg/dtDJmq2eck
