### ISSUE TITLE
Панель часов перестала поддаваться изменениям настроек

### ISSUE THREAD

**Issue by Internetx777max** [Armagomen/battle_observer#24]
Часы не выключаются, не меняют своё положение и не меняют свой вид при изменении форматирования строки.
Ни через настройки мода в ангаре, ни через ручную замену значений в конфиге панель часов не поддаётся настройке. Она просто зависла.

The clock does not turn off, does not change its position and does not change its appearance when the string formatting changes.
Neither through the mod settings in the hangar, nor through manual replacement of values ​​in the config, the clock panel can be configured. She just hung up.

**Comment by Kurzdor** [comment]
Установлена 1.39.0.
Изменение форматирования строки в ангаре - работает. Изменение позиционирования требует перезахода на сервер либо захода и выхода в любых подменю в ангаре (магазин, задания, ЛБЗ и т. д.)

**Comment by Kurzdor** [comment]
Исправлено в 88358c0964ac2db192f02442499edf36258bae3c
Добавил изменение на лету из под настроек в ангаре.
