### ISSUE TITLE
Battle observer Zoom

### ISSUE THREAD

**Issue by Issamito** [Armagomen/battle_observer#5]
Hello,
I try to use mod but last version which was working for me just fine was: BattleObserver_1.32.4. Every new releases has the same bug, When enabled AUTOZOOM (automatic selection of the zoom ratio...) in battle when I click on mouse middle button (which is assigned as switching to sniper mode) no sniper mode is entering and everything is getting lock. Can't turn the camera view (I"m able to drive tank, make turn, but can't chnage view point moving mouse, I can make shot but sight is hard locked on nothing), can't get out from battle using Esc key and so on. The sight is locked on nearest hard point. And no way to get out of this. All other mod configs are turned off. Just want to use auto-zoom. Version 1.32.4 still works great. Regards.

**Comment by Armagomen** [comment]
check in 1.35.2 release and give me screenshot of your settings and python.log file if don't work again.

**Comment by Armagomen** [comment]
fixed in 1.35.4

**Comment by Issamito** [comment]
OK, I will play and I will let you know if it is OK now..

**Comment by Issamito** [comment]
Yep now everything works just fine. Thx.
