### ISSUE TITLE
Repainting icons does not work after v1.36.5

### ISSUE THREAD

**Issue by Kazfyx** [Armagomen/battle_observer#9]
**Describe the bug**
Repaint icons option under the statistics block does not work in the ears, it only works on the TAB window.

**Comment by Kazfyx** [comment]
Since v1.36.8, repainting tank icons no longer has any effect, no matter in the ears or on the tab window.

**Comment by Armagomen** [comment]
check in 1.36.9
if you use XVM statistics and icons are disabled for compatibility
